### PR TITLE
Updated chai to version 3.3.0

### PR DESCRIPTION
**Pull request by wulfsolter**
:rocket:

One of your dependencies has just updated, so this PR bumps the corresponding version number in your `package.json`.

You can now check that the dependency update doesn't break your code, and then release the new version of your software safe in the knowledge that it will stay in this working state, regardless of _when_ your users do `$ npm install`.

Have a good day!

---

This pull request was created by [greenkeeper.io](http://greenkeeper.io/).
It keeps your software, up to date, all the time.

<sub>
Tired of seeing this sponsor message? Upgrade to the supporter plan!
You'll also get your pull requests faster :zap:
</sub>

### CODE REVIEW

**Comment by wulfsolter** [comment]
Whoops! Seems there was a small glitch in thegreenkeeper.io system! Apologies!

> Hello Wulf, 
> 
> we had a problem with a GitHub API client that was shared in memory between our pull-request creation jobs, which caused false attribution under rare >conditions.
> 
> Unfortunately we have sent one such pull-request in your name:
> 
> https://github.com/kentcdodds/invoke-filter/pull/7
> 
> Once we were aware of the problem we immediately stopped all machines until we could resolve the problem. At no time did anyone have unauthorized access to >repositories.
> 
> We are sorry for the caused problems and confusion.
> 
> Best,
> 
> Stephan
> 
> Stephan Bönnemann
> Greenkeeper / greenkeeper.io, by
> The Neighbourhoodie Software GmbH
> Adalbertstr. 7-8, 10999 Berlin
> neighbourhood.ie
> 
> Handelsregister HRB 157851 B Amtsgericht Charlottenburg
> Geschäftsführung: Jan Lehnardt, Lena Reinhard

**Comment by kentcdodds** [comment]
Yeah, oh well :-) Thanks for the contribution? ;-)

**Comment by wulfsolter** [comment]
Thanks to a bot glitch, I've found a new angular perf optimisation tool :-) Keep up the good work!

**Comment by kentcdodds** [comment]
Sweet! :dancer: cc @boennemann good things can come out of glitches. Don't feel too bad buddy :-)

**Comment by kentcdodds** [comment]
Hey! And I've totally used `mongo-express` before. Small world! Neat-o! You keep up the good work too #highFive

**Pull request closed without merging**
